# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcppeigen_hello_world <- function() {
    .Call('finemap_rcppeigen_hello_world', PACKAGE = 'finemap')
}

rcppeigen_outerproduct <- function(x) {
    .Call('finemap_rcppeigen_outerproduct', PACKAGE = 'finemap', x)
}

rcppeigen_innerproduct <- function(x) {
    .Call('finemap_rcppeigen_innerproduct', PACKAGE = 'finemap', x)
}

rcppeigen_bothproducts <- function(x) {
    .Call('finemap_rcppeigen_bothproducts', PACKAGE = 'finemap', x)
}

